version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./:/mnt/extra-addons
    command: >
      odoo
      -c /etc/odoo/odoo.conf
      --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
    restart: always

volumes:
  db_data: 